### ISSUE TITLE
Do tags based on Plexpy version

### ISSUE THREAD

**Issue by InAnimaTe** [PHLAK/docker-plexpy#1]
Thanks a lot for this awesome image. Not big on the `linuxserver.io` built one.

One thing I'd like for the docker images is to be able to pull a tag parallel to the version of PlexPy installed on the image.

Thanks!

**Comment by PHLAK** [comment]
Good idea.  I just pushed a tag for the current (1.4.17) version and will try to remember to do this for all future versions as well.
